import { test, expect } from '@playwright/test';

test.describe('Verify Email URL', () => {
  test.setTimeout(60000);

  test('verification email URL should match the Angular verify-email route', async ({ request, page }) => {
    const ts = Date.now();
    const email = `verifyurl-${ts}@example.com`;

    // Register
    await request.post('http://localhost:5299/api/auth/register', {
      data: { fullName: 'Verify User', email, password: 'S3cur3P@ss!', organizationName: `VerCorp${ts}` },
      timeout: 60000,
    });

    // Get the verification token
    const tokenResp = await request.get(`http://localhost:5299/api/auth/test/verification-token?email=${encodeURIComponent(email)}`);
    const { token } = await tokenResp.json();

    // The verification URL generated by the email service is:
    // http://localhost:4200/verify-email?token=...
    // Navigate to this URL and check if it reaches the verify-email component
    await page.goto(`http://localhost:4200/verify-email?token=${encodeURIComponent(token)}`, { waitUntil: 'networkidle' });
    await page.waitForTimeout(2000);

    // The page should show verification content (not a blank/404 page)
    const pageText = await page.locator('body').textContent();
    expect(pageText).toMatch(/[Vv]erif/); // Contains "Verif" (from Verification, Verify, etc.)
  });
});
